//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accessories.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB : DbContext
    {
        public DB()
            : base("name=DB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Accessory> Accessories { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<color> colors { get; set; }
        public virtual DbSet<Statue> Statues { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<SubCat1> SubCat1 { get; set; }
        public virtual DbSet<SubCat2> SubCat2 { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
    }
}
